"""initial

Revision ID: 143f3af0fc07
Revises: 
Create Date: 2026-04-04 20:48:51.842720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143f3af0fc07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('students',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('availability',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('study_groups',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('meeting_mode', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['courses.cid'], ),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('group_members',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['study_groups.gid'], ),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['study_groups.gid'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('group_members')
    op.drop_table('study_groups')
    op.drop_table('availability')
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
