"""empty message

Revision ID: 642de3a802af
Revises: 143f3af0fc07
Create Date: 2026-04-06 04:03:38.789085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '642de3a802af'
down_revision = '143f3af0fc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('availability_sid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint('uq_group_member', ['gid', 'sid'])
        batch_op.drop_constraint(batch_op.f('group_members_sid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_members_gid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_groups', ['gid'], ['gid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_gid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['sender_id'], ['sid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'study_groups', ['gid'], ['gid'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.alter_column('group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('study_groups_cid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['cid'], ['cid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('study_groups_cid_fkey'), 'courses', ['cid'], ['cid'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_gid_fkey'), 'study_groups', ['gid'], ['gid'])
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'students', ['sender_id'], ['sid'])
        batch_op.alter_column('sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('message_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_members_gid_fkey'), 'study_groups', ['gid'], ['gid'])
        batch_op.create_foreign_key(batch_op.f('group_members_sid_fkey'), 'students', ['sid'], ['sid'])
        batch_op.drop_constraint('uq_group_member', type_='unique')
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('availability_sid_fkey'), 'students', ['sid'], ['sid'])
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
